module.exports = thousandMultiples = [
  "",
  "thousand ",
  "million",
  "milliard",
  "billion",
  "billiard",
  "trillion",
  "quadrillion",
  "quintillion",
  "sextillion",
  "کوینتیلیون",
  "کوانتینیارد",
  "سکستیلیون",
  "سکستیلیارد",
  "سپتیلیون",
  "سپتیلیارد",
  "اکتیلیون",
  "اکتیلیارد",
  "نانیلیون",
  "نانیلیارد",
  "دسیلیون",
  "دسیلیارد",
  "گوگول",
  "گوگول پلکس",
  "گوگول پلکسیان"
];
